name: 'Silverstripe Cloud Dashboard API Service'
description: 'Interact with the Silverstripe Cloud Dashboard'
inputs:
  dash-api-username:
    description: 'Username to authenticate with the dashboard API'
    required: true
  dash-api-token:
    description: 'API token to authenticate with the dashboard API'
    required: true
  dash-stack-name:
    description: 'Short name for your stack (check the URL in Dash)'
    required: true
  dash-env-name:
    description: 'Which env to interact with (usually UAT or Production'
    required: true
  bypass-level:
    description: 'What level of bypass power to give this deployment [none, approval, start]'
    default: 'none'
    required: false
  debug:
    description: 'Show debug output'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: layers
  color: blue
